services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: moments
        MYSQL_PASSWORD: 12345678
    ports:
        - "3308:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom-network
  java:
    image: moments-soap-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./target/soap-service-1.0-SNAPSHOT.jar:/app/soap-service-1.0-SNAPSHOT.jar
      - ./target/soap-service-1.0-SNAPSHOT-jar-with-dependencies.jar:/app/soap-service-1.0-SNAPSHOT-jar-with-dependencies.jar
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge